plugins {
    id 'java'
    id 'idea'
    id 'java-library'
    id 'org.springframework.boot' version '3.3.4'
    id 'io.spring.dependency-management' version '1.1.6'
}
group = 'com.gilgamesh.common'
version = '0.0.1'

dependencies {
    implementation 'com.github.f4b6a3:uuid-creator:6.1.1'
    api 'org.apache.httpcomponents.client5:httpclient5:5.6'
}
